name: Assignment CI

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run assignment files of functional programming
        run: |
          npx ts-node functional-programming/Higher_Order_function.ts
          npx ts-node functional-programming/Higher_Order_function2.ts
          npx ts-node functional-programming/Higher_Order_function_3.ts

      - name: Run linting
        run: npm run lint

      # Post-Browser project tests
      - name: Post-Browser Install dependencies & Playwright
        working-directory: Post-Browser-assignment
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Post-Browser Run Playwright tests
        working-directory: Post-Browser-assignment
        run: npx playwright test --timeout=60000

      # Drumkit project tests
      - name: Drumkit Install dependencies & Playwright
        working-directory: drumkit-project
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Drumkit Run Playwright tests
        working-directory: drumkit-project
        run: npx playwright test --timeout=60000
