name: Assignment CI

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run assignment files of functional programming
        run: |
          npx ts-node functional-programming/Higher_Order_function.ts
          npx ts-node functional-programming/Higher_Order_function2.ts
          npx ts-node functional-programming/Higher_Order_function_3.ts

      - name: Run linting
        run: npm run lint

      # Testing project
      - name: Install dependencies in project folder
        working-directory: Post-Browser-assignment
        run: npm install

      - name: Install Playwright Browsers
        working-directory: Post-Browser-assignment
        run: npx playwright install --with-deps

      - name: Run project tests
        working-directory: Post-Browser-assignment
        run: npx playwright test
